# Generated by Django 6.0.1 on 2026-07-03 07:57

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(max_length=200, verbose_name='Должность')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('photo', models.ImageField(upload_to='content/director/', verbose_name='Фото')),
                ('photo_cropping', image_cropping.fields.ImageRatioField('photo', '400x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область фото для блока директора.', hide_image_field=False, size_warning=True, verbose_name='Кадрирование фото')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директор',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопрос-ответ',
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Alt-текст')),
                ('image', models.ImageField(upload_to='content/gallery/', verbose_name='Фото')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1200x800', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Выберите фрагмент для отображения в сетке галереи.', hide_image_field=False, size_warning=True, verbose_name='Кадрирование фото')),
                ('grid_class', models.CharField(choices=[('md:col-span-1', '1 колонка'), ('md:col-span-2', '2 колонки'), ('md:col-span-2 md:row-span-2', '2×2 (крупная)')], default='md:col-span-1', max_length=64, verbose_name='Размер в сетке')),
                ('title_size', models.CharField(choices=[('lg', 'Малый'), ('xl', 'Средний'), ('2xl', 'Крупный')], default='lg', max_length=8, verbose_name='Размер заголовка')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Например: 1-4 или 5-9', max_length=16, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=64, verbose_name='Подпись фильтра')),
                ('note', models.TextField(verbose_name='Примечание под тарифами')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Группа тарифов',
                'verbose_name_plural': 'Группы тарифов',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('vk_url', models.URLField(verbose_name='Ссылка ВКонтакте')),
                ('vk_label', models.CharField(default='darovanie34', max_length=64, verbose_name='Подпись VK')),
                ('yandex_map_script', models.TextField(help_text='Вставьте script из конструктора карт Яндекса.', verbose_name='Код карты Яндекс')),
                ('map_status', models.CharField(default='Мы открыты', max_length=64, verbose_name='Статус на карте')),
                ('legacy_url', models.URLField(blank=True, verbose_name='Ссылка на старый сайт')),
                ('footer_tagline', models.TextField(default='Образовательный центр, где учеба в радость. Индивидуальный подход и комфортная среда для каждого ребенка.', verbose_name='Описание в футере')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
                'verbose_name_plural': 'Контакты сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
                ('group', models.CharField(choices=[('nav', 'Шапка сайта'), ('footer_school', 'Футер — о центре'), ('footer_doc', 'Футер — документы')], db_index=True, max_length=20, verbose_name='Раздел')),
                ('label', models.CharField(max_length=120, verbose_name='Текст ссылки')),
                ('href', models.CharField(max_length=200, verbose_name='URL / якорь')),
            ],
            options={
                'verbose_name': 'Ссылка сайта',
                'verbose_name_plural': 'Ссылки сайта',
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(max_length=200, verbose_name='Должность / предмет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(choices=[('purple', 'Фиолетовый'), ('blue', 'Синий'), ('fuchsia', 'Фуксия'), ('indigo', 'Индиго'), ('green', 'Зелёный')], default='purple', max_length=16, verbose_name='Цвет акцента')),
                ('photo', models.ImageField(upload_to='content/teachers/', verbose_name='Фото')),
                ('avatar_cropping', image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область фото для круглого аватара в слайдере.', hide_image_field=False, size_warning=True, verbose_name='Кадрирование аватара')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
                'ordering': ['sort_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Пункт')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='landing.director', verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Преимущество директора',
                'verbose_name_plural': 'Преимущества директора',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.CharField(help_text='Например: 25 000', max_length=32, verbose_name='Цена')),
                ('original_price', models.CharField(blank=True, max_length=32, verbose_name='Старая цена')),
                ('icon', models.CharField(default='📅', max_length=8, verbose_name='Иконка')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='landing.pricingtier', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
