# Generated by Django 5.1.15 on 2026-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('landing', 'Главная страница'), ('popup', 'Всплывающая форма'), ('callback', 'Обратный звонок')], db_index=True, default='landing', max_length=20, verbose_name='Источник')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=150, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=150, verbose_name='UTM Content')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Реферер')),
                ('landing_page', models.CharField(blank=True, max_length=255, verbose_name='Страница')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
