# Generated by Django 5.1.15 on 2026-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Путь')),
                ('event_type', models.CharField(choices=[('page_view', 'Просмотр страницы'), ('cta_click', 'Клик по CTA'), ('form_start', 'Начало заполнения формы'), ('theme_toggle', 'Переключение темы')], db_index=True, default='page_view', max_length=20, verbose_name='Тип события')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Сессия')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='UTM Campaign')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Реферер')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx'), models.Index(fields=['utm_campaign', 'created_at'], name='analytics_p_utm_cam_7cf6b7_idx')],
            },
        ),
    ]
